version: '2'
networks:
  micronet:
services:
  consul1:
    image: gliderlabs/consul
    container_name: consul1
    ports:
     - "8400:8400"
     - "8500:8500"
     - "8600:8600/udp"
    networks:
      - micronet
    command: ["agent", "-server", "-bootstrap-expect=1", "-data-dir=/tmp/consul", "-node=consul1", "-client=0.0.0.0", "-ui"]

  cassandra:
    image: mashape/cassandra
    container_name: kong-database
    ports:
     - 9042:9042
    networks:
      - micronet

  kong:
    image: mashape/kong
    restart: always
    container_name: kong
    hostname: api.labic.net
    ports:
     - 8000:8000
     - 8001:8001
    networks:
      - micronet
    links:
     - cassandra

  microservice1:
    image: antifragilesoftware/simple-boot-microservice
    container_name: microservice1
    ports:
     - "8080:8080"
    depends_on:
     - consul1
    networks:
      - micronet
    command: ["java","--spring.cloud.consul.host=consul1","-Djava.security.egd=file:/dev/./urandom","-jar","/microservice.jar"]
